name: Genrate ASCII Artwork

on : push 

jobs: 
    ascii_job:
        runs-on : ubuntu-latest
        steps:
         - name: checkout
           uses: actions/checkout@v7

         - name: install cowsay program
           run: sudo apt install cowsay -y

         - name: Generate ASCII Artwork
           run: cowsay -f dragon "Run for a cover i am a elephant....RAWR" > dragon.txt

         - name: test file exist
           run: grep -i "dragon" dragon.txt

         - name: read file
           run: cat dragon.txt

         - name: list repo list
           run: ls -ltra