name: My first workflow

on : push 

jobs: 
    first_job:
        runs-on : ubuntu-latest
        steps:
         - name: welcome message
           run: echo "my first job"

         - name: list files
           run: ls
