name: My first workflow

on : push 

jobs: 
    first_job:
        runs-on : ubuntu-latest
        steps:
         - name: checkout
           uses: actions/checkout@v7
         - name: welcome message
           run: |
            echo "my first job"
            ls -ltra
            cat README.md
        #  - name: list files
        #    run: ls
        #  - name : Read file
        #    run: cat README.md